version: "3.7"
services:
    backend:
        build:
            context: ./
            dockerfile: ./backend.Dockerfile
        container_name: backend
        ports:
            - "8000:8000"
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./data:/data/db
          

    
  
