# Generated by Django 3.2.5 on 2021-07-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('director_name', models.CharField(blank=True, default='', max_length=100)),
                ('cast', models.JSONField(default={})),
                ('published_year', models.IntegerField(blank=True, default=0)),
                ('released_date', models.CharField(blank=True, default='', max_length=10)),
                ('overview', models.TextField(blank=True, default='')),
                ('vote_average', models.CharField(blank=True, default='', max_length=10)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('movie_cover', models.TextField(blank=True, default='')),
                ('genre', models.JSONField(default={})),
                ('netflix_link', models.TextField(blank=True, default='')),
                ('youtube_link', models.TextField(blank=True, default='')),
                ('poster_cover', models.TextField(blank=True, default='')),
                ('backdrop_cover', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('updated_by', models.CharField(blank=True, default='', max_length=100)),
                ('moods', models.JSONField(default={})),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('artist_name', models.CharField(blank=True, default='', max_length=100)),
                ('album_name', models.CharField(blank=True, default='', max_length=100)),
                ('published_year', models.IntegerField(blank=True, default=0)),
                ('released_date', models.CharField(blank=True, default='', max_length=10)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('album_cover', models.TextField(blank=True, default='')),
                ('genre', models.JSONField(default={})),
                ('spotify_link', models.TextField(blank=True, default='')),
                ('youtube_link', models.TextField(blank=True, default='')),
                ('soundcloud_link', models.TextField(blank=True, default='')),
                ('moods', models.JSONField(default={})),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
