# Generated by Django 3.2.5 on 2021-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
