# Generated by Django 3.2.5 on 2021-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
