# Generated by Django 3.2.5 on 2021-07-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210712_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_cover',
            field=models.TextField(blank=True, default=''),
        ),
    ]
