# Generated by Django 3.2.5 on 2021-07-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210712_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
