# Generated by Django 3.2.5 on 2021-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20210712_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='moods',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.JSONField(default={}),
        ),
    ]
