# Generated by Django 3.2.5 on 2021-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_movie_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genius_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
